global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.0.101:8080'] # Change for whatever you use.
